### ISSUE TITLE
Fix package.json

### ISSUE THREAD

**Issue by munkhbolde** [socketio/socket.io-p2p#21]

**Comment by munkhbolde** [comment]
`https://registry.npmjs.org/socket.io-p2p-parser`

**Comment by munkhbolde** [comment]
that is my  `npm install` error log
`npm http 404 https://registry.npmjs.org/socket.io-p2p-parser
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-62-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/nothing/socketio/web/socket.io-p2p
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nothing/socketio/web/socket.io-p2p/npm-debug.log
npm ERR! not ok code 0`

**Comment by tomcartwrightuk** [comment]
Are you getting this when installing master? What version of node are you on? What command are you running that causes this?

**Comment by munkhbolde** [comment]
`npm install`  and my node version is v0.10.25

**Comment by tomcartwrightuk** [comment]
I have been unable to recreate this with the current master version of this repo. What is the latest commit on your local copy? What architecture are you on?

**Comment by utan** [comment]
same error for me..
When I call npm socket.io-p2p same result and even downloading from master is same,  

specs : 
Ubuntu 14.04 X64 , NODE v0.10.25 , NPM 1.3.10.. 

I won't be able to test it.. very unfortunate..
