### ISSUE TITLE
TypeError: fns[i] is not a function

### ISSUE THREAD

**Issue by SlutYeah** [socketio/socket.io-p2p#29]
This error originates in the namespace.js file inside of the socket.io module. This happens when io.use(p2p) has been called and another person attempts to connect. This happens both for my own socket.io project and the chat example that I used to debug the original issue. I used browserify both times to create my bundle.js file and have made only minor modifications to the require('') commands in the index.js file(inside socket.io-p2p-master) to elucidate the path for the node.js modules. Below is the run function inside namespace.js (which is where the error occurs). I'm not sure exactly what files are relevant but I've attached is my bundle.js file that I generated using browserify. I've gotten this error for my original project and the example so it may be my machine (windows) but I'm wondering if anyone else has had this problem as well.
```
Namespace.prototype.run = function(socket, fn){
  var fns = this.fns.slice(0);
  if (!fns.length) return fn(null);

  function run(i){
    fns[i](socket, function(err){        //this is the line that causes the error

      // upon error, short-circuit
      if (err) return fn(err);

      // if no middleware left, summon callback
      if (!fns[i + 1]) return fn(null);

      // go on to next
      run(i + 1);
    });
  }

  run(0);
};



```
[bundle.zip](https://github.com/socketio/socket.io-p2p/files/384807/bundle.zip)

**Comment by SlausB** [comment]
Seems like **io.use( 'some literal', function(){} )** used instead of **io.use( function(){} )** when migrated to socket >1.0.

**Comment by PramodMahajan14** [comment]
I have been getting this error when I applying authorization middleware - io.use(authorizerUser)

**Comment by vlad-theletsgoapp** [comment]
> I have been getting this error when I applying authorization middleware - io.use(authorizerUser)

Same issue at:
```
/node_modules/socket.io/dist/namespace.js:124
            fns[i](socket, function (err) {
                  ^

TypeError: fns[i] is not a function
    at run (.../node_modules/socket.io/dist/namespace.js:124:19)
    at Namespace.run (.../node_modules/socket.io/dist/namespace.js:135:9)
    at Namespace._add (.../node_modules/socket.io/dist/namespace.js:211:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.6.0
```

And the caller code:
```
io = socketIo(server, {
    maxHttpBufferSize: 1e7 // 10 MB (default is 1 MB)
});

// Commenting out the line below solves this issue:
io.use(authSocket); // Use middleware to authenticate user and set socket.user object
io.on('connection', (socket) => {
...
```
